---
  env:
    node: true
    mocha: true
    es6: true

  ecmaFeatures:
    modules: true

  extends: eslint:recommended

  rules:
    # console for debug
    no-console: 0

    # Strict mode
    strict:
      - 0
      - "never"

    # possible errors
    no-unexpected-multiline: 2

    # best practice
    no-native-reassign: 2
    no-caller: 2
    no-eval: 2
    no-multi-str: 2
    no-labels: 2
    no-lone-blocks: 2
    no-loop-func: 2
    no-param-reassign: 2
    no-useless-concat: 2
    no-useless-call: 2
    no-proto: 2
    no-with: 2
    # curly: 2
    eqeqeq: 2


    # Stylistic Issues
    indent:
      - 2
      - 4
      - SwitchCase: 1

    object-curly-spacing:
      - 2
      - always
      - objectsInObjects: false
        arraysInObjects: false
    space-infix-ops: 0
    space-unary-ops: 0
    keyword-spacing: 2
    block-spacing: 2
    brace-style:
      - 2
      - 1tbs
      - allowSingleLine: true
    comma-spacing: 2
    camelcase: 2
    comma-style: 2
    semi: 2
    semi-spacing: 2
    quotes:
      - 2
      - single
    linebreak-style:
      - 2
      - unix
    no-nested-ternary: 2
    max-nested-callbacks:
      - 2
      - 4
    no-spaced-func: 2
    no-trailing-spaces: 2
    no-unneeded-ternary: 2

    # es6
    arrow-spacing: 2
    no-class-assign: 2
    no-const-assign: 2
    no-dupe-class-members: 2
